### ISSUE TITLE
Does not build using vite + vue

### ISSUE THREAD

**Issue by foxxyz** [foxxyz/ws-plus#13]
When attempting a build using Vite + Vue, the following error will prevent build:

```
[13:06] path > npm run build

> app@1.0.0 build
> vite build

building for production...
✓ 1076 modules transformed.
'reactive' is not exported by node_modules/ws-plus/vue.js, imported by node_modules/ws-plus/vue.js
file: /path/node_modules/ws-plus/vue.js:2:41
1: import { Client } from '.'
2: import { inject, onMounted, onUnmounted, reactive } from 'vue'
                                            ^
3:
4: export function createSocket(url, options) {
error during build:
Error: 'reactive' is not exported by node_modules/ws-plus/vue.js, imported by node_modules/ws-plus/vue.js
    at error (/path/node_modules/rollup/dist/shared/rollup.js:5275:30)
    at Module.error (/path/node_modules/rollup/dist/shared/rollup.js:9992:16)
    at Module.traceVariable (/path/node_modules/rollup/dist/shared/rollup.js:10385:29)
    at ModuleScope.findVariable (/path/node_modules/rollup/dist/shared/rollup.js:8843:39)
    at FunctionScope.findVariable (/path/node_modules/rollup/dist/shared/rollup.js:2637:38)
    at ChildScope.findVariable (/path/node_modules/rollup/dist/shared/rollup.js:2637:38)
    at Identifier$1.bind (/path/node_modules/rollup/dist/shared/rollup.js:4013:40)
    at CallExpression$1.bind (/path/node_modules/rollup/dist/shared/rollup.js:2724:23)
    at CallExpression$1.bind (/path/node_modules/rollup/dist/shared/rollup.js:6726:15)
    at VariableDeclarator.bind (/path/node_modules/rollup/dist/shared/rollup.js:2724:23)
```

seems like Rollup is confusing the `ws-plus/vue.js` module with the general `vue` module from `node_modules`.

**Comment by foxxyz** [comment]
After further research, not Rollup's fault, but Vite's `vite:resolve` module resolution plugin. More specifically, the way it resolves modules for packages with the `browser` field set in `package.json`.

More info here: https://github.com/vitejs/vite/issues/2115

At this point it seems like there are two options:

 1. Wait for Vite to fix the issue
 2. Break backwards compatibility by renaming the vue plugin module to something else than `vue.js`.

**Comment by foxxyz** [comment]
Looks like [Vite has fixed the issue](https://github.com/vitejs/vite/commit/de58967c570822e7a345bb63b81ca113ed8a8127), no action needed on our side. Closing...
